# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DATABASE_PORT") { "5432" } %>

development:
  <<: *default
  database: ink_receipts_development

test:
  <<: *default
  database: ink_receipts_test

production:
  <<: *default
  database: ink_receipts_production
  url: <%= ENV["DATABASE_URL"] %>