#!/usr/bin/env python3
from __future__ import annotations

import argparse
import re
import subprocess
from struct import unpack
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
LEGACY_RELEASE_TERMS = (
    "HybridTDA",
    "hybridtda",
    "pip install hybridtda",
    "mair_manifest.v1.json",
    "assurance_receipt.v1.json",
    "backend_comparison.v1.json",
)
ACTIVE_DOC_GLOBS = (
    "README.md",
    "CONTRIBUTING.md",
    "RELEASING.md",
    "REPRODUCIBILITY.md",
    "SECURITY.md",
    "FORMAL_SEMANTICS.md",
    "docs/**/*.md",
    "products/*/README.md",
    "products/*/docs/*.md",
    "packages/*/README.md",
    "rust/crates/*/README.md",
    "web/*/README.md",
    ".github/RELEASE_TEMPLATE.md",
)
ARCHIVE_FRAGMENT = str(Path("docs") / "archive")
ACTIVE_DOC_FORBIDDEN_SUBSTRINGS = (
    "pip install blkbx-lab",
    "pip install --pre blkbx-lab",
    "published package name: `blkbx-lab`",
    "- published package name: `blkbx-lab`",
    "- package: `blkbx-lab`",
    "package surface: `blkbx-lab`",
    "install blkbx-lab",
    "use `blkbx-lab` for the published package",
    "Use `blkbx-lab` for the published package",
    "ink_manifest.v1.json",
    "ink_receipt.v1.json",
    "receipt_comparison.v1.json",
)
UNSUPPORTED_COMMAND_RE = re.compile(r"\b(?:blkbx-lab|mechlab)\s+(?:export|ingest|replay|hook|scan|bundle)\b")
MARKDOWN_LINK_RE = re.compile(r"!?\[[^\]]*\]\(([^)]+)\)")
ABSOLUTE_PATH_MARKERS = ("/Volumes/", "/Users/")
QWEN_APPENDIX_MARKER = "## Reproducibility Appendix"
RELEASE_TEMPLATE_PATH = ".github/RELEASE_TEMPLATE.md"
HOST_SOCIAL_PREVIEW = ROOT / "assets" / "brand" / "og-card.png"
VALIDATION_REPORT = ROOT / "docs" / "research" / "qwen35-validation-report.md"


def _check(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def ensure_clean_worktree() -> None:
    result = subprocess.run(
        ["git", "status", "--short"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    _check(not result.stdout.strip(), "git worktree is not clean")


def _active_doc_surfaces() -> list[Path]:
    seen: set[Path] = set()
    surfaces: list[Path] = []
    for pattern in ACTIVE_DOC_GLOBS:
        for path in sorted(ROOT.glob(pattern)):
            if not path.is_file():
                continue
            if ARCHIVE_FRAGMENT in str(path.relative_to(ROOT)):
                continue
            if path in seen:
                continue
            seen.add(path)
            surfaces.append(path)
    return surfaces


def ensure_active_doc_terms() -> None:
    for path in _active_doc_surfaces():
        text = path.read_text(encoding="utf-8")
        for token in LEGACY_RELEASE_TERMS:
            _check(token not in text, f"{token!r} found in {path.relative_to(ROOT)}")
        for token in ACTIVE_DOC_FORBIDDEN_SUBSTRINGS:
            _check(token not in text, f"{token!r} found in active doc {path.relative_to(ROOT)}")
        _check(
            UNSUPPORTED_COMMAND_RE.search(text) is None,
            f"unsupported CLI verb found in active doc {path.relative_to(ROOT)}",
        )


def ensure_active_doc_links_resolve() -> None:
    for path in _active_doc_surfaces():
        text = path.read_text(encoding="utf-8")
        for raw_target in MARKDOWN_LINK_RE.findall(text):
            target = raw_target.strip().strip("<>").split("#", maxsplit=1)[0]
            if not target:
                continue
            if "://" in target or target.startswith(("mailto:", "/")):
                continue
            resolved = (path.parent / target).resolve()
            _check(resolved.exists(), f"broken relative link {raw_target!r} in {path.relative_to(ROOT)}")


def ensure_qwen_report_scopes_absolute_paths() -> None:
    report = VALIDATION_REPORT.read_text(encoding="utf-8")
    _check(QWEN_APPENDIX_MARKER in report, "Qwen validation report is missing the reproducibility appendix marker")
    main_body, appendix = report.split(QWEN_APPENDIX_MARKER, maxsplit=1)
    for marker in ABSOLUTE_PATH_MARKERS:
        _check(marker not in main_body, f"absolute path marker {marker!r} appears before the Qwen appendix")
    _check(any(marker in appendix for marker in ABSOLUTE_PATH_MARKERS), "Qwen appendix no longer records exact local paths")


def ensure_release_workflow_uses_authored_notes() -> None:
    workflow = (ROOT / ".github" / "workflows" / "release.yml").read_text(encoding="utf-8")
    _check(f"body_path: {RELEASE_TEMPLATE_PATH}" in workflow, "release workflow does not use the authored release template")
    _check("generate_release_notes: true" not in workflow, "release workflow still relies on autogenerated release notes")
    _check("assets/brand/og-card.png" in workflow, "release workflow does not upload the host-ready social preview asset")
    _check("pypa/gh-action-pypi-publish@release/v1" in workflow, "release workflow does not publish tagged distributions to PyPI")
    _check("name: pypi" in workflow, "release workflow is missing the pypi environment")
    _check("id-token: write" in workflow, "release workflow is missing the id-token permission required for trusted publishing")
    _check("https://pypi.org/p/mechlab-sdk" in workflow, "release workflow does not point to the mechlab-sdk PyPI project")


def ensure_host_ready_assets() -> None:
    _check(HOST_SOCIAL_PREVIEW.exists(), "host-ready social preview asset is missing: assets/brand/og-card.png")
    with HOST_SOCIAL_PREVIEW.open("rb") as handle:
        header = handle.read(24)
    _check(header.startswith(b"\x89PNG\r\n\x1a\n"), "host-ready social preview asset is not a PNG file")
    width, height = unpack(">II", header[16:24])
    _check((width, height) == (1280, 640), "host-ready social preview asset must be 1280x640")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate documentation and repo ergonomics release readiness.")
    parser.add_argument(
        "--skip-clean-worktree",
        action="store_true",
        help="Skip the clean git worktree check. Use only for local in-progress validation.",
    )
    args = parser.parse_args(argv)

    if not args.skip_clean_worktree:
        ensure_clean_worktree()
    ensure_active_doc_terms()
    ensure_active_doc_links_resolve()
    ensure_qwen_report_scopes_absolute_paths()
    ensure_host_ready_assets()
    ensure_release_workflow_uses_authored_notes()
    print("release readiness checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
