#!/usr/bin/env python3
from __future__ import annotations

import argparse
import subprocess
from struct import unpack
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
PUBLIC_RELEASE_SURFACES = (
    ROOT / "README.md",
    ROOT / "RELEASING.md",
    ROOT / "docs" / "pypi.md",
    ROOT / "docs" / "qwen35-validation-report.md",
    ROOT / "docs" / "release-readiness.md",
    ROOT / ".github" / "RELEASE_TEMPLATE.md",
)
FORBIDDEN_RELEASE_TERMS = ("HybridTDA", "hybridtda", "pip install hybridtda")
ABSOLUTE_PATH_MARKERS = ("/Volumes/", "/Users/")
QWEN_APPENDIX_MARKER = "## Reproducibility Appendix"
RELEASE_TEMPLATE_PATH = ".github/RELEASE_TEMPLATE.md"
HOST_SOCIAL_PREVIEW = ROOT / "assets" / "brand" / "og-card.png"


def _check(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(message)


def ensure_clean_worktree() -> None:
    result = subprocess.run(
        ["git", "status", "--short"],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    _check(not result.stdout.strip(), "git worktree is not clean")


def ensure_public_release_terms() -> None:
    for path in PUBLIC_RELEASE_SURFACES:
        text = path.read_text(encoding="utf-8")
        for token in FORBIDDEN_RELEASE_TERMS:
            _check(token not in text, f"{token!r} found in {path.relative_to(ROOT)}")


def ensure_qwen_report_scopes_absolute_paths() -> None:
    report = (ROOT / "docs" / "qwen35-validation-report.md").read_text(encoding="utf-8")
    _check(QWEN_APPENDIX_MARKER in report, "Qwen validation report is missing the reproducibility appendix marker")
    main_body, appendix = report.split(QWEN_APPENDIX_MARKER, maxsplit=1)
    for marker in ABSOLUTE_PATH_MARKERS:
        _check(marker not in main_body, f"absolute path marker {marker!r} appears before the Qwen appendix")
    _check(any(marker in appendix for marker in ABSOLUTE_PATH_MARKERS), "Qwen appendix no longer records exact local paths")


def ensure_release_workflow_uses_authored_notes() -> None:
    workflow = (ROOT / ".github" / "workflows" / "release.yml").read_text(encoding="utf-8")
    _check(f"body_path: {RELEASE_TEMPLATE_PATH}" in workflow, "release workflow does not use the authored release template")
    _check("generate_release_notes: true" not in workflow, "release workflow still relies on autogenerated release notes")
    _check("assets/brand/og-card.png" in workflow, "release workflow does not upload the host-ready social preview asset")


def ensure_host_ready_assets() -> None:
    _check(HOST_SOCIAL_PREVIEW.exists(), "host-ready social preview asset is missing: assets/brand/og-card.png")
    with HOST_SOCIAL_PREVIEW.open("rb") as handle:
        header = handle.read(24)
    _check(header.startswith(b"\x89PNG\r\n\x1a\n"), "host-ready social preview asset is not a PNG file")
    width, height = unpack(">II", header[16:24])
    _check((width, height) == (1280, 640), "host-ready social preview asset must be 1280x640")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate documentation and repo ergonomics release readiness.")
    parser.add_argument(
        "--skip-clean-worktree",
        action="store_true",
        help="Skip the clean git worktree check. Use only for local in-progress validation.",
    )
    args = parser.parse_args(argv)

    if not args.skip_clean_worktree:
        ensure_clean_worktree()
    ensure_public_release_terms()
    ensure_qwen_report_scopes_absolute_paths()
    ensure_host_ready_assets()
    ensure_release_workflow_uses_authored_notes()
    print("release readiness checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
