pub const RECEIPT_TRANSCRIPT_LEGACY_V1_DOMAIN: &[u8] = b"INK-CORE-TRANSCRIPT-V1";
pub const RECEIPT_TRANSCRIPT_TLV_V2_DOMAIN: &[u8] = b"INK-CORE-TLV-V2";
pub const MODEL_WAIST_DOMAIN: &[u8] = b"INK-MODEL-WAIST-V1";
pub const RUNTIME_DOMAIN: &[u8] = b"INK-RUNTIME-CLAIM-V1";
pub const FACTS_DOMAIN: &[u8] = b"INK-POLICY-FACTS-V1";
