pub const RECEIPT_TRANSCRIPT_DOMAIN: &[u8] = b"INK-CORE-TRANSCRIPT-V1";
pub const MODEL_WAIST_DOMAIN: &[u8] = b"INK-MODEL-WAIST-V1";
pub const RUNTIME_DOMAIN: &[u8] = b"INK-RUNTIME-CLAIM-V1";
pub const FACTS_DOMAIN: &[u8] = b"INK-POLICY-FACTS-V1";
