#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Error {
    EmptyValue,
    ValueTooLong,
    ContainsNul,
    InvalidByteClass,
    InvalidUtf8,
    InvalidTimestamp,
    InvalidRuntimeShape,
    InvalidModelShape,
    TooManyArtifacts,
    TooManyControls,
    TooManyReasons,
    TooManyRules,
    TooManyConditionNodes,
    InvalidRuleRoot,
    InvalidConditionIndex,
    InvalidConditionShape,
    InvalidConditionCycle,
    InvalidRequestedOutputShape,
    InvalidTokenUsageTotals,
    InconsistentReceiptPayload,
    SignatureError,
}
